### ISSUE TITLE
When don't get "Origin Fee" in Bridge page, the submit button better not clickable 

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1004]
[Video link](https://drive.google.com/file/d/1rTQtPF_mdyFNMOclBJemEXjNCP4qfh0V/view?usp=sharing)

When the "Origin Fee" shows "--", when I try to click the "Submit", there is no response

![截屏2023-05-06 下午5.03.24.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/56c9d9e9-3c58-4213-8924-8d2c4717ea9c)

**Comment by Kevingislason** [comment]
I'm not sure what the correct behavior is here. I think the current behavior is possibly okay since fees shouldn't take much longer to load than balances. We could gray out the button when it is not intractable, but I think the button flickering could be a little distracting. This is probably a question for Chloe.
