### ISSUE TITLE
The AI picture on the Generated page is repeated twice

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#540]
![截屏2023-02-20 下午8.28.41.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/448dbfa8-71ef-4b29-a9f8-d14277ba2113)

[Video link](https://drive.google.com/file/d/1oo5eR75_uAeTbRSg_1-cT8jYKMJZCu7C/view?usp=sharing)

**Comment by zhangjing28** [comment]
This is just the loop effect of this component, I think it is fit the design

**Comment by zhangjing28** [comment]
> Can we get rid of one so that we don't have a repetitive picture showing at the same time? thank you!!!

That's actually not repeated. It is just influenced by loop props. Loop means when you have an image list like`[ img1, img2, img3]`, The front end will render with `[img3, img1, img2, img3, img1]`. I think that's acceptable, not a bug

**Comment by yeyeyeyehan** [comment]
I think from a user's perspective it looks repetitive because it's showing 2 identical pictures on both end, it might cause confusion since each picture should be different when users generate. I think it's acceptable at the moment if we don't have enough time implementing/changing this, we can always fix it later. it's not that crucial at this point ;)

**Comment by zhangjing28** [comment]
> I think from a user's perspective it looks repetitive because it's showing 2 identical pictures on both end, it might cause confusion since each picture should be different when users generate. I think it's acceptable at the moment if we don't have enough time implementing/changing this, we can always fix it later. it's not that crucial at this point ;)

It won't cause many efforts, I will remove the loop props

**Comment by yeyeyeyehan** [comment]
thank you!
